# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d65d4934991efe4ebdbc0d712c3b3e3f91643ed97c9a852d12e4e08d42c694623308e119092813f029b9f54913d39fe22f491b2f62c64669fb470806c38dbe3b

test:
  secret_key_base: 88588b5fae5a0fbf7370e64b96694329c3b75e9eff12359e336be0f6072dff7790762666634a6cb40710ac55ef461b79cce3c83358c5329baa27b627eec00801

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
