# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7032dcf2d23f73c82ea64b17e6f439ec65c6607fb6986659e90667d049dd0e686c251bf4add2e6de523bd902a0d30cef9027b1632238621a64524be79d92ae23

test:
  secret_key_base: 287abaf3640df9ffca734efbd0d695907d09cfc93ee874c1d6aea84a2f6dab9c400fff275852d5439e3f286322a5dbf2592761835487230096d07375898ef164

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
